### ISSUE TITLE
Blockchain and Smart Contracts Platforms

### ISSUE THREAD

**Issue by Siimone** [m-u-g/eventi#11]
Ciao a tutti!
Sono **Simone Da Re**, co-founder di **Coiners.it**
Sono stato contattato da Francesco un po' di tempo fa per portare un piccolo **talk su Blockchain**, questa tecnologia che sta portando davvero tanto hype :D
Dopo essere stato a Roma, Verona e Vicenza, portare Blockchain nella community di **MUG** a **Treviso** sarebbe davvero forte, cosa ne pensate?

Per qualsiasi domanda potete trovarmi su un po' tutti i social
[LinkedIn](https://www.linkedin.com/in/simonedare/)
[Telegram](https://t.me/SimoneDaRe)
[Facebook](https://www.facebook.com/simone.dare)
[Instagram](https://www.instagram.com/simonedare_/)
[Twitter](https://twitter.com/DareSimone)

**Comment by francesco-strazzullo** [comment]
@Siimone potresti aggiungere il materiale del talk a questo repo? Così chiudiamo la issue
