### ISSUE TITLE
The art of composition

### ISSUE THREAD

**Issue by francesco-strazzullo** [m-u-g/eventi#2]
_From @marcosh on February 24, 2018 8:52_

L'arte di comporre cose ci permette di costruire cose complesse partendo da componenti semplici. Inoltre avere componenti semplici facilmente componibili ci permette di ottenere l'agognata capacità di riutilizzare parti del codice che abbiamo già scritto.

La disciplina che studia e formalizza i meccanismi che regolano la composizione viene chiamata dai matematici "teoria delle categorie".

L'idea sarebbe descrivere le basi di teoria delle categorie e cercare di capire perchè questa può essere rilevante e interessante per un programmatore. Di conseguenza dovranno essere introdotti alcuni concetti di programmazione funzionale, che potrebbero essere esemplificati e testati con un po' di codice.

Sarebbe bello cercare di rendere la serata interattiva, anche se non mi è ancora chiarissimo come...

Una serata del genere potrei gestirla io, oppure si potrebbe provare a contattare Giulio Canti (https://twitter.com/GiulioCanti), che ne sa un sacco di queste cose

_Copied from original issue: coding-jam/eventi#3_

**Comment by francesco-strazzullo** [comment]
_From @P3trur0 on February 24, 2018 10:22_

:heart: :heart: oppure Bartosz Milewski :heart:

**Comment by ubaldop** [comment]
Event selected by MUG members today! :champagne: Check out on our Slack for further information.

**Comment by francesco-strazzullo** [comment]
Here you can find the info about the event https://www.eventbrite.it/e/biglietti-the-art-of-composition-45371201485

**Comment by ubaldop** [comment]
It was a :boom: !
