### ISSUE TITLE
Introduction to Web Components

### ISSUE THREAD

**Issue by francesco-strazzullo** [m-u-g/eventi#8]
Components are the main feature of every modern frontend frameworks out there. From React to Vue, but also the good old AngularJS in the latest versions has a nice API for components.

There's also a standard way to create components for the web, without the help of any framework. We just need to use a set of W3C API that forms the Web Components API.

During the talk, we are going to see in detail the pros and the cons of this API with a series of examples. 

You can find some example here https://github.com/francesco-strazzullo/custom-components-example

**Comment by ubaldop** [comment]
Evento scelto dai membri del gruppo, ma in attesa di essere pianificato per i prossimi mesi.

**Comment by francesco-strazzullo** [comment]
Evento pianificato per il 13 Settembre https://www.eventbrite.it/e/biglietti-introduzione-ai-webcomponents-48330829813
